-- @TODO fix later
ALTER TYPE ACTIVITY_TYPE RENAME TO ACTIVITY_TYPE_OLD;
CREATE TYPE ACTIVITY_TYPE AS ENUM ('listing', 'sale', 'update_price');

ALTER TABLE activities
    ALTER COLUMN activity_type TYPE ACTIVITY_TYPE USING activity_type::ACTIVITY_TYPE;

DROP TYPE ACTIVITY_TYPE;
